# Overlay Companion MCP - Container Infrastructure (KasmVNC)
#
# This stack uses KasmVNC as the remote desktop backend.
# Legacy Guacamole stack has been removed per project direction.
#
# Features:
# ✅ No external database required
# ✅ Multi-monitor support
# ✅ Fewer containers and simpler configuration

version: "3.8"
services:
  # Remote desktop: KasmVNC service (preferred)

  # New default: KasmVNC service (preferred)
  kasmvnc:
    build:
      context: ..
      dockerfile: infra/Dockerfile.kasmvnc
    environment:
      # Ports can be customized per user via env
      KASM_PORT: ${KASM_PORT:-6901}
    ports:
      - "${KASMVNC_PORT:-6080}:6901"
      - "${KASMVNC_ADMIN_PORT:-3000}:3000"
    restart: unless-stopped

  mcp-server:
    build:
      context: ..
      dockerfile: infra/Dockerfile.mcp
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:3000
      # Prefer KasmVNC; provide API URL for health/metadata
      KASMVNC_URL: http://kasmvnc:6901
      KASMVNC_API_URL: http://kasmvnc:3000
    ports:
      - "${MCP_PORT:-3000}:3000"
    depends_on:
      - kasmvnc
    restart: unless-stopped

  overlay-web:
    build:
      context: ..
      dockerfile: infra/Dockerfile.web
    environment:
      PORT: 8080
      MCP_SERVER_URL: http://mcp-server:3000
      # Remote desktop URL (KasmVNC)
      KASMVNC_URL: http://kasmvnc:6901
    ports:
      - "${WEB_PORT:-8082}:8080"  # Custom overlay web interface
    depends_on:
      - mcp-server
      - kasmvnc
    restart: unless-stopped

  caddy:
    image: docker.io/library/caddy:2.8.4
    ports:
      - "${CONTAINER_PORT:-8080}:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - mcp-server
      - overlay-web
      - kasmvnc
    restart: unless-stopped

volumes:
  pgdata:
