version: "3.8"
services:
  postgres:
    image: docker.io/library/postgres:16-alpine
    environment:
      POSTGRES_USER: guacamole
      POSTGRES_PASSWORD: guacpass
      POSTGRES_DB: guacamole_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  guacd:
    image: docker.io/guacamole/guacd:1.5.5
    restart: unless-stopped

  guacamole:
    image: docker.io/guacamole/guacamole:1.5.5
    depends_on:
      - postgres
      - guacd
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole
      POSTGRES_PASSWORD: guacpass
    ports:
      - "8081:8080" # Expose Guacamole web (Tomcat) on 8081 locally
    restart: unless-stopped

  guac-init:
    image: docker.io/alpine:3.19
    depends_on:
      - guacamole
    environment:
      GUAC_BASE_URL: http://guacamole:8080/guacamole
      GUAC_ADMIN_USER: ${GUAC_ADMIN_USER:-guacadmin}
      GUAC_ADMIN_PASS: ${GUAC_ADMIN_PASS:-guacadmin}
      GUAC_CONN_NAME: ${GUAC_CONN_NAME:-fedora-vm}
      GUAC_RDP_HOST: ${GUAC_RDP_HOST:-vm.example.local}
      GUAC_RDP_PORT: ${GUAC_RDP_PORT:-3389}
      GUAC_RDP_USERNAME: ${GUAC_RDP_USERNAME:-}
      GUAC_RDP_PASSWORD: ${GUAC_RDP_PASSWORD:-}
      GUAC_RDP_DOMAIN: ${GUAC_RDP_DOMAIN:-}
      GUAC_RDP_SECURITY: ${GUAC_RDP_SECURITY:-any}
      GUAC_RDP_IGNORE_CERT: ${GUAC_RDP_IGNORE_CERT:-true}
      GUAC_RDP_WIDTH: ${GUAC_RDP_WIDTH:-1920}
      GUAC_RDP_HEIGHT: ${GUAC_RDP_HEIGHT:-1080}
    volumes:
      - ./scripts:/scripts:ro
    entrypoint: ["/bin/sh","-c"]
    command: "apk add --no-cache curl >/dev/null && /bin/sh /scripts/guac-init.sh"
    restart: "no"

  mcp:
    build:
      context: ..
      dockerfile: infra/Dockerfile.mcp
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:3000
    ports:
      - "3000:3000"
    depends_on:
      - guacamole
    restart: unless-stopped

  caddy:
    image: docker.io/library/caddy:2.8.4
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - mcp
      - guacamole
    restart: unless-stopped

volumes:
  pgdata:
