name: Build and Push Container Images to GHCR

on:
  push:
    branches: [main, develop]
    paths:
      - 'infra/**'
      - 'src/**'
      - 'Dockerfile*'
      - '.github/workflows/container-registry.yml'
  pull_request:
    branches: [main]
    paths:
      - 'infra/**'
      - 'src/**'
      - 'Dockerfile*'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build even without changes'
        required: false
        default: 'false'
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_MCP: ${{ github.repository }}/mcp-server
  IMAGE_NAME_WEB: ${{ github.repository }}/web-interface

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      version-tag: ${{ steps.version.outputs.version }}
      pr-tag: ${{ steps.version.outputs.pr_tag }}

    strategy:
      matrix:
        include:
          - name: mcp-server
            dockerfile: infra/Dockerfile.mcp
            context: .
            image_env: IMAGE_NAME_MCP
          - name: web-interface
            dockerfile: infra/Dockerfile.web
            context: .
            image_env: IMAGE_NAME_WEB

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version tag
        id: version
        run: |
          # Generate date-based version: YYYY.MM.DD.quantity
          DATE=$(date +%Y.%m.%d)

          # Get existing tags for today to determine quantity
          EXISTING_TAGS=$(git tag -l "${DATE}.*" | wc -l)
          QUANTITY=$((EXISTING_TAGS + 1))

          VERSION="${DATE}.${QUANTITY}"

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "date=${DATE}" >> $GITHUB_OUTPUT
          echo "quantity=${QUANTITY}" >> $GITHUB_OUTPUT

          echo "Generated version: ${VERSION}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.image_env == 'IMAGE_NAME_MCP' && env.IMAGE_NAME_MCP || env.IMAGE_NAME_WEB }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=${{ matrix.name }}
            org.opencontainers.image.description=Overlay Companion MCP - ${{ matrix.name }}
            org.opencontainers.image.version=${{ steps.version.outputs.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          outputs: type=registry
          provenance: false

      - name: Create Git tag
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "${{ steps.version.outputs.version }}" -m "Release ${{ steps.version.outputs.version }}"
          git push origin "${{ steps.version.outputs.version }}"

  cleanup-old-images:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        image: [mcp-server, web-interface]

    steps:
      - name: Delete old container versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.repository }}/${{ matrix.image }}
          package-type: container
          min-versions-to-keep: 10
          delete-only-untagged-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}

  security-scan:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      security-events: write

    strategy:
      matrix:
        image: [mcp-server, web-interface]

    steps:
      - name: Determine image tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "tag=${{ needs.build-and-push.outputs.pr-tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ needs.build-and-push.outputs.version-tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.image }}:${{ steps.tag.outputs.tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
